name: linux containers windows

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Set up WSL2
        uses: vedantmgoyal9/setup-wsl2@v1.1.0
        with:
          distro: Ubuntu

      - name: Run LS on ubuntu
        run: ls
        shell: wsl-run {0}

      - name: run pwd on ubuntu
        run: pwd
        shell: wsl-run {0}
