name: linux containers windows

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Set up WSL2
        uses: vedantmgoyal9/setup-wsl2@v1.1.0
        with:
          distro: Ubuntu

      - name: Update package lists
        run: sudo apt-get update
        shell: wsl-run {0}

      - name: Install Docker
        run: |
          sudo apt-get install -y docker.io
          sudo usermod -aG docker $USER
        shell: wsl-run {0}

      - name: Start Docker service
        run: sudo service docker start
        shell: wsl-run {0}

      - name: Run a Linux container
        run: docker run --rm alpine uname -a
        shell: wsl-run {0}
