name: Desktop Screenshot

on:
  workflow_dispatch:

jobs:
  screenshot-mac:
    runs-on: macos-latest

    steps:
    - name: Capture desktop screenshot
      run: |
        screencapture -x screenshot-mac.png

    - name: Upload screenshot as artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot-mac
        path: screenshot-mac.png

  screenshot-windows:
    runs-on: windows-latest

    steps:
    - uses: OrbitalOwen/desktop-screenshot-action@0.1
      with:
          file-name: 'screenshot-win-1.jpg'

    - name: Upload screenshot as artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot-win-1
        path: screenshot-win-1.jpg
